[package]
name = "zero2prod_axum"
version = "0.1.0"
authors = ["David Kalliecharan"]
edition = "2021"
license = "Apache-2.0 or BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
