addr = "127.0.0.1"
port = 9000
base_url = "127.0.0.1"

[database]
name = "demo.db"

[email_client]
base_url = "localhost"
sender_email = "test@example.com"
authorization_token = "my-secret-token"
timeout_milliseconds = 10000
